version: "3"
services:

  station1:
    build:
      context: .
      dockerfile: station/Dockerfile
    networks:
      - stations
    environment:
      - STATION_NUM=1
      - STATIONS_TOTAL=3

  station2:
    build:
      context: .
      dockerfile: station/Dockerfile
    networks:
      - stations
    environment:
      - STATION_NUM=2
      - STATIONS_TOTAL=3

  station3:
    build:
      context: .
      dockerfile: station/Dockerfile
    networks:
    - stations
    environment:
    - STATION_NUM=3
    - STATIONS_TOTAL=3

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    depends_on:
      - station1
      - station2
      - station3
    networks:
      - stations
    environment:
      - COUNTRY=AR
      - FREQUENCY=100
      - STATIONS_TOTAL=3

networks:
  stations: